### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by little-Paul-3** [iscas3dv/deformshape#1]
Hi @BaowenZ , Thank you very much for your work. We are quite interested in this work. However, when attempting to replicate it, we noticed a continuous increase in the program's GPU memory usage, eventually resulting in an 'Out of Memory' error. Upon investigation, we identified that it might be due to line 301 in flexfield.py:
`local_rigid_measurement, direction_transformer, differential_det, differential_singular = utils.Differential_Relevant_Terms.apply(grad_deform, 1, 1e-1)`

This seems to be causing the spike in GPU memory. Have you encountered a similar situation? If so, how was it eventually resolved?

Looking forward to your reply.

**Comment by BaowenZ** [comment]
Hi! I recommend to reduce ```batch_size``` and ```on_surface_points``` in config files. The following setting works well on a single RTX3060 with pytorch=2.0.1
```jsx
batch_size: 2
epochs: 5
epochs_til_checkpoint: 5
expand: -1
experiment_name: 50002_train
hidden_num: 128
latent_dim: 128
hyper_hidden_layers: 3
part_num: 20
logging_root: ./logs
lr: 0.0001
max_points: 50000
model_type: sine
on_surface_points: 1000
point_cloud_root: data/train_data/
train_split_root: split/train
subject_group_id: [50002]
steps_til_summary: 1000
```

**Comment by little-Paul-3** [comment]
Hi, @BaowenZ. Thanks for your reply! I wonder which torchmeta version you installed. I met some problems when installing pytorch 2.0.1

**Comment by zy-lazytitan** [comment]
> Hi, @BaowenZ. Thanks for your reply! I wonder which torchmeta version you installed. I met some problems when installing pytorch 2.0.1

Our torchmeta version is 1.8.0, hopefully that will solve your problem.

**Comment by little-Paul-3** [comment]
Hi, @zy-lazytitan. Thanks for your reply!
It mentioned that **comment out line 3 in pytorch-meta/torchmeta/datasets/utils.py** in READ.ME.
I founded there was no need to comment out line 3 in torchmeta1.8.0. 
However, when I ran `train.py` it occured an error: `ImportError: cannot import name '_get_confirm_token' from 'torchvision.datasets.utils (/home/anaconda3/envs/deformshape/lib/python3.9/site-packages/torchvision/datasets/utils.py)'` .

I founded that it was because in torchmeta1.8.0 `pytorch-meta/torchmeta/datasets/utils.py` called the function : `from torchvision.datasets.utils import _get_confirm_token, _save_response_content`:

```
import os
import json
def get_asset_path(*args):
    basedir = os.path.dirname(__file__)
    return os.path.join(basedir, 'assets', *args)
def get_asset(*args, dtype=None):
    filename = get_asset_path(*args)
    if not os.path.isfile(filename):
        raise IOError('{} not found'.format(filename))
    if dtype is None:
        _, dtype = os.path.splitext(filename)
        dtype = dtype[1:]
    if dtype == 'json':
        with open(filename, 'r') as f:
            data = json.load(f)
    else:
        raise NotImplementedError()
    return data

from torchvision.datasets.utils import _get_confirm_token, _save_response_content
def _quota_exceeded(response: "requests.models.Response"):
    return False
    # See https://github.com/pytorch/vision/issues/2992 for details
    # return "Google Drive - Quota exceeded" in response.text
def download_file_from_google_drive(file_id, root, filename=None, md5=None):
    """Download a Google Drive file from  and place it in root.
    Args:
        file_id (str): id of file to be downloaded
        root (str): Directory to place downloaded file in
        filename (str, optional): Name to save the file under. If None, use the id of the file.
        md5 (str, optional): MD5 checksum of the download. If None, do not check
    """
    # Based on https://stackoverflow.com/questions/38511444/python-download-files-from-google-drive-using-url
    import requests
    url = "https://docs.google.com/uc?export=download"

    root = os.path.expanduser(root)
    if not filename:
        filename = file_id
    fpath = os.path.join(root, filename)

    os.makedirs(root, exist_ok=True)

    if os.path.isfile(fpath) and check_integrity(fpath, md5):
        print('Using downloaded and verified file: ' + fpath)
    else:
        session = requests.Session()

        response = session.get(url, params={'id': file_id}, stream=True)
        token = _get_confirm_token(response)

        if token:
            params = {'id': file_id, 'confirm': token}
            response = session.get(url, params=params, stream=True)

        if _quota_exceeded(response):
            msg = (
                f"The daily quota of the file {filename} is exceeded and it "
                f"can't be downloaded. This is a limitation of Google Drive "
                f"and can only be overcome by trying again later."
            )
            raise RuntimeError(msg)

        _save_response_content(response, fpath)
```

 And I have no idea about it, should I comment out? Have you encountered a similar situation?

By the way, my environment is: pytorch=2.0.1, torchvision=0.15.2, cuda=11.7, torchmeta=1.8.0.
Thank you very much!

**Comment by zy-lazytitan** [comment]
> from torchvision.datasets.utils import _get_confirm_token, _save_response_content

Sorry for that, I have encountered the same situation and I commented out that line `from torchvision.datasets.utils import _get_confirm_token, _save_response_content`

**Comment by BaowenZ** [comment]
Thanks you! @little-Paul-3  It seems our README doesn't match the code of torchmeta. So, I add the version of torchmeta to the README.

**Comment by Frreed** [comment]
> Hi @BaowenZ , Thank you very much for your work. We are quite interested in this work. However, when attempting to replicate it, we noticed a continuous increase in the program's GPU memory usage, eventually resulting in an 'Out of Memory' error. Upon investigation, we identified that it might be due to line 301 in flexfield.py: `local_rigid_measurement, direction_transformer, differential_det, differential_singular = utils.Differential_Relevant_Terms.apply(grad_deform, 1, 1e-1)`
> 
> This seems to be causing the spike in GPU memory. Have you encountered a similar situation? If so, how was it eventually resolved?
> 
> Looking forward to your reply.

Hi, i want to ask you a question. How does you generate the dataset, did you follow this work's script ? i try to generate data following this work, but generate 1 data needs over 1 mins. did this problem also happened to you ?
